/**
 * Emotional arc kept for curation order:
 * edge → words → way back
 */
export const tracks = [
  {
    id: 'mausam',
    title: 'Mausam',
    artist: 'Mithoon',
    film: 'The Train',
    youtubeId: 'NlEaUHfunMI',
    chapter: 'edge',
  },
  {
    id: 'abhi-abhi',
    title: 'Abhi Abhi',
    artist: 'KK',
    film: 'Jism 2',
    youtubeId: 'y49NPSJcRjA',
    chapter: 'edge',
  },
  {
    id: 'toh-phir-aao',
    title: 'Toh Phir Aao',
    artist: 'Mustafa Zahid',
    film: 'Awarapan',
    youtubeId: 'h5-Kq9k3zeo',
    chapter: 'edge',
  },
  {
    id: 'zara-sa',
    title: 'Zara Sa',
    artist: 'KK',
    film: 'Jannat',
    youtubeId: 'ZsAOnmByy38',
    chapter: 'edge',
  },
  {
    id: 'maahi',
    title: 'Maahi',
    artist: 'Toshi Sabri',
    film: 'Raaz — The Mystery Continues',
    youtubeId: 'e1edxTqJnKk',
    chapter: 'words',
  },
  {
    id: 'tera-mera-rishta',
    title: 'Tera Mera Rishta',
    artist: 'Mustafa Zahid',
    film: 'Awarapan',
    youtubeId: '0J0HZrDvbjY',
    chapter: 'words',
  },
  {
    id: 'hamari-adhuri-kahani',
    title: 'Hamari Adhuri Kahani',
    artist: 'Arijit Singh',
    film: 'Hamari Adhuri Kahani',
    youtubeId: 'f3FFOBrMmdg',
    chapter: 'words',
  },
  {
    id: 'pal',
    title: 'Pal',
    artist: 'Arijit Singh, Shreya Ghoshal',
    film: 'Jalebi',
    youtubeId: 'aDFEb_W2t1Y',
    chapter: 'words',
  },
  {
    id: 'phir-mohabbat',
    title: 'Phir Mohabbat',
    artist: 'Mohammed Irfan, Saim Bhat, Arijit Singh',
    film: 'Murder 2',
    youtubeId: 'm1rcse8INWk',
    chapter: 'words',
  },
  {
    id: 'beete-lamhe',
    title: 'Beete Lamhe',
    artist: 'KK',
    film: 'The Train',
    youtubeId: 'UlacMvx_VYk',
    chapter: 'back',
  },
  {
    id: 'bhula-dena',
    title: 'Bhula Dena',
    artist: 'Mustafa Zahid',
    film: 'Aashiqui 2',
    youtubeId: 'II4CvWvgIsI',
    chapter: 'back',
  },
]
