/**
 * Full Spotify Zindagi.wtf (2) order — 32 tracks (lofi Beete Lamhein skipped).
 * Emotional arc: edge → words → back
 */
export const tracks = [
  {
    id: 'mausam',
    title: 'Mausam',
    artist: 'Mithoon',
    film: 'The Train',
    youtubeId: 'NlEaUHfunMI',
    chapter: 'edge',
    whisper: 'The weather changed the day you left.',
  },
  {
    id: 'abhi-abhi',
    title: 'Abhi Abhi',
    artist: 'KK',
    film: 'Jism 2',
    youtubeId: 'y49NPSJcRjA',
    chapter: 'edge',
    whisper: 'Just now — and already too late.',
  },
  {
    id: 'aasan-nahin-yahan',
    title: 'Aasan Nahin Yahan',
    artist: 'Arijit Singh',
    film: 'Aashiqui 2',
    youtubeId: 'aNToVeBBKn4',
    chapter: 'edge',
    whisper: 'Nothing about staying was easy.',
  },
  {
    id: 'beete-lamhein',
    title: 'Beete Lamhein',
    artist: 'KK',
    film: 'The Train',
    youtubeId: 'UlacMvx_VYk',
    chapter: 'edge',
    whisper: 'The hours that already happened keep playing.',
  },
  {
    id: 'jadu-hai-nasha-hai',
    title: 'Jadu Hai Nasha Hai',
    artist: 'Shreya Ghoshal',
    film: 'Lamhe',
    youtubeId: 'T_MPeEX-aIs',
    chapter: 'edge',
    whisper: 'A spell you never asked to break.',
  },
  {
    id: 'sau-dard',
    title: 'Sau Dard',
    artist: 'Sonu Nigam',
    film: 'Jaan-E-Mann',
    youtubeId: 'xo8JU-Vc1C0',
    chapter: 'edge',
    whisper: 'A hundred aches, one quiet room.',
  },
  {
    id: 'maahi',
    title: 'Maahi',
    artist: 'Toshi Sabri',
    film: 'Raaz — The Mystery Continues',
    youtubeId: 'e1edxTqJnKk',
    chapter: 'edge',
    whisper: 'Your name still fits the silence.',
  },
  {
    id: 'pyaar-ke-pal',
    title: 'Pyaar Ke Pal',
    artist: 'KK',
    film: 'Hum Rahe Ya Na Rahe Kal',
    youtubeId: 'NUqlCJTYu6I',
    chapter: 'edge',
    whisper: 'Love was only ever a handful of moments.',
  },
  {
    id: 'tujhe-yaad-na-meri-aayee',
    title: 'Tujhe Yaad Na Meri Aayee',
    artist: 'Udit Narayan, Manpreet Akhtar',
    film: 'Kuch Kuch Hota Hai',
    youtubeId: 'HeFM4VFZL1M',
    chapter: 'words',
    whisper: 'I remembered you. You didn’t have to.',
  },
  {
    id: 'ae-ajnabi',
    title: 'Ae Ajnabi',
    artist: 'Udit Narayan, Mahalakshmi',
    film: 'Dil Se',
    youtubeId: 'BP0YPNed4fk',
    chapter: 'words',
    whisper: 'Stranger — why do you still feel like home?',
  },
  {
    id: 'chaaha-hai-tujhko',
    title: 'Chaaha Hai Tujhko',
    artist: 'Udit Narayan, Anuradha Paudwal',
    film: 'Mann',
    youtubeId: '0gcOqr6nsxE',
    chapter: 'words',
    whisper: 'Wanting you was the whole story.',
  },
  {
    id: 'ab-naam-mohabbat',
    title: 'Ab Naam Mohabbat',
    artist: 'Udit Narayan, Alka Yagnik',
    film: 'Ghulam',
    youtubeId: 'QKgG9kyWmLg',
    chapter: 'words',
    whisper: 'Call it love. Call it what broke.',
  },
  {
    id: 'tera-mera-rishta',
    title: 'Tera Mera Rishta',
    artist: 'Mustafa Zahid',
    film: 'Awarapan',
    youtubeId: '0J0HZrDvbjY',
    chapter: 'words',
    whisper: 'Whatever we were is still unfinished.',
  },
  {
    id: 'ya-ali',
    title: 'Ya Ali',
    artist: 'Zubeen Garg',
    film: 'Gangster',
    youtubeId: 'ReRBW9hTSY0',
    chapter: 'words',
    whisper: 'A prayer when words run out.',
  },
  {
    id: 'jag-soona-soona-lage',
    title: 'Jag Soona Soona Lage',
    artist: 'Rahat Fateh Ali Khan, Richa Sharma',
    film: 'Om Shanti Om',
    youtubeId: '4BjGoXdpk2o',
    chapter: 'words',
    whisper: 'The whole world went hollow.',
  },
  {
    id: 'kal-ho-naa-ho-sad',
    title: 'Kal Ho Naa Ho — Sad',
    artist: 'Sonu Nigam, Alka Yagnik',
    film: 'Kal Ho Naa Ho',
    youtubeId: 'FSI1y2Ti5fA',
    chapter: 'words',
    whisper: 'Tomorrow was never promised.',
  },
  {
    id: 'teri-deewani',
    title: 'Teri Deewani',
    artist: 'Kailash Kher',
    film: 'Kailasa',
    youtubeId: '3R-q79a7n98',
    chapter: 'words',
    whisper: 'Madness that still knows your shape.',
  },
  {
    id: 'maula-mere-lele-meri-jaan',
    title: 'Maula Mere Lele Meri Jaan',
    artist: 'Krishna Beuraa, Salim Merchant',
    film: 'Chak De! India',
    youtubeId: 'gBWSRhrgNm4',
    chapter: 'words',
    whisper: 'Take what’s left. It’s already yours.',
  },
  {
    id: 'hamari-adhuri-kahani',
    title: 'Hamari Adhuri Kahani',
    artist: 'Arijit Singh',
    film: 'Hamari Adhuri Kahani',
    youtubeId: 'f3FFOBrMmdg',
    chapter: 'words',
    whisper: 'Our story never got an ending.',
  },
  {
    id: 'aye-khuda',
    title: 'Aye Khuda',
    artist: 'Saim Bhat, Mithoon',
    film: 'Murder 2',
    youtubeId: 'sqkX-SBixss',
    chapter: 'words',
    whisper: 'Asking the sky what you wouldn’t answer.',
  },
  {
    id: 'tujhe-bhula-diya',
    title: 'Tujhe Bhula Diya',
    artist: 'Mohit Chauhan, Shekhar Ravjiani, Shruti Pathak',
    film: 'Anjaana Anjaani',
    youtubeId: 'o-9VdyXZKsQ',
    chapter: 'back',
    whisper: 'I said I forgot you. I lied.',
  },
  {
    id: 'rabba-main-toh-mar-gaya-oye',
    title: 'Rabba Main Toh Mar Gaya Oye',
    artist: 'Rahat Fateh Ali Khan',
    film: 'Mausam',
    youtubeId: 'T3W7DT3EMb0',
    chapter: 'back',
    whisper: 'Something in me didn’t survive the leaving.',
  },
  {
    id: 'baatein-ye-kabhi-na',
    title: 'Baatein Ye Kabhi Na',
    artist: 'Arijit Singh',
    film: 'Khamoshiyan',
    youtubeId: 'iKopExw_3Zg',
    chapter: 'back',
    whisper: 'Things we never said out loud.',
  },
  {
    id: 'tu-hi-haqeeqat',
    title: 'Tu Hi Haqeeqat',
    artist: 'Javed Ali',
    film: 'Tum Mile',
    youtubeId: '2CAiycLVy7s',
    chapter: 'back',
    whisper: 'You were the only real thing.',
  },
  {
    id: 'piya-aaye-na',
    title: 'Piya Aaye Na',
    artist: 'Tulsi Kumar, KK',
    film: 'Aashiqui 2',
    youtubeId: 'M2CZaOwOeQo',
    chapter: 'back',
    whisper: 'Waiting for a door that stays shut.',
  },
  {
    id: 'zara-sa',
    title: 'Zara Sa',
    artist: 'KK',
    film: 'Jannat',
    youtubeId: 'ZsAOnmByy38',
    chapter: 'back',
    whisper: 'A little closer would have been enough.',
  },
  {
    id: 'tu-hai-ki-nahi',
    title: 'Tu Hai Ki Nahi',
    artist: 'Ankit Tiwari',
    film: 'Roy',
    youtubeId: 'SeSbwS34PgY',
    chapter: 'back',
    whisper: 'Are you here — or only in the song?',
  },
  {
    id: 'tere-bin',
    title: 'Tere Bin',
    artist: 'Atif Aslam',
    film: 'Bas Ek Pal',
    youtubeId: '7jbqQi5XSP4',
    chapter: 'back',
    whisper: 'Without you, the night is longer.',
  },
  {
    id: 'zaroorat',
    title: 'Zaroorat',
    artist: 'Mustafa Zahid',
    film: 'Ek Villain',
    youtubeId: 'eA7V16oogFA',
    chapter: 'back',
    whisper: 'Need that never learned to leave.',
  },
  {
    id: 'baarish',
    title: 'Baarish',
    artist: 'Mohammed Irfan, Gajendra Verma',
    film: 'Yaariyan',
    youtubeId: 'CrL3h1Bq0Iw',
    chapter: 'back',
    whisper: 'Rain on the glass. Same old ache.',
  },
  {
    id: 'banjaara',
    title: 'Banjaara',
    artist: 'Mohammed Irfan',
    film: 'Ek Villain',
    youtubeId: '0NFxcNheoLc',
    chapter: 'back',
    whisper: 'Still wandering the same streets.',
  },
  {
    id: 'aadat',
    title: 'Aadat',
    artist: 'Atif Aslam',
    film: 'Kalyug / Jal',
    youtubeId: 'tjsckg5t1k8',
    chapter: 'back',
    whisper: 'Habit dressed up as love.',
  },
]
